import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import * as path from 'path';
import {
    INIT_COMMAND,
    classifyRequirementsFile,
    collectMainIncludes,
    convertChoices,
    convertCommands,
    convertPrompt,
    displayCommand,
    requirementIncludes,
    requirementNames,
    shellArg,
} from '../convert';

test('classifyRequirementsFile: runtime requirements', () => {
    for (const file of [
        'requirements.txt',
        '/repo/requirements.txt',
        '/repo/requirements/base.txt',
        '/repo/requirements/production.txt',
        '/repo/requirements-prod.txt',
        '/repo/requirements_common.txt',
        '/repo/deps/base.txt',
        '/repo/requirements.in',
    ]) {
        assert.equal(classifyRequirementsFile(file), 'main', file);
    }
});

test('classifyRequirementsFile: development requirements', () => {
    for (const file of [
        '/repo/requirements-dev.txt',
        '/repo/requirements_dev.txt',
        '/repo/requirements/dev.txt',
        '/repo/requirements/development.txt',
        '/repo/requirements/local.txt',
        '/repo/requirements-test.txt',
        '/repo/requirements_tests.txt',
        '/repo/requirements/docs.txt',
        '/repo/requirements-lint.txt',
        '/repo/requirements-dev-py311.txt',
        '/repo/Requirements-Dev.txt',
        '/repo/dev-requirements.txt',
    ]) {
        assert.equal(classifyRequirementsFile(file), 'dev', file);
    }
});

test('classifyRequirementsFile: names that say neither', () => {
    assert.equal(classifyRequirementsFile('/repo/requirements-ml.txt'), 'other');
    assert.equal(classifyRequirementsFile('/repo/requirements/gpu.txt'), 'other');
    assert.equal(classifyRequirementsFile('/repo/requirements-base-py39.txt'), 'other');
});

test('requirementIncludes: every spelling of -r, and nothing else', () => {
    const text = `-r requirements.txt
-rbase.txt
--requirement common.txt
--requirement=shared/extra.txt
-r "with space.txt"  # quoted, with a comment
-c constraints.txt
--constraint constraints.txt
-e .
-r https://example.com/requirements.txt
# -r commented-out.txt
pytest>=8
`;
    assert.deepEqual(requirementIncludes(text), [
        'requirements.txt',
        'base.txt',
        'common.txt',
        'shared/extra.txt',
        'with space.txt',
    ]);
});

test('requirementIncludes: a continued line is read as one', () => {
    assert.deepEqual(requirementIncludes('-r \\\nrequirements.txt\n'), ['requirements.txt']);
});

test('requirementNames: names as uv writes them, options and paths skipped', () => {
    const text = `# Runtime
Django>=4.2,<5.0
requests[socks]==2.32.3 ; python_version >= "3.9"
typing_extensions
zope.interface>=6
pkg-from-url @ https://example.com/pkg-1.0.tar.gz
uvloop==0.21.0; sys_platform != "win32"  # not on Windows
-r base.txt
-c constraints.txt
-e ./libs/local
--index-url https://pypi.org/simple
./libs/other
https://example.com/wheel-1.0-py3-none-any.whl
git+https://github.com/example/repo.git#egg=repo
local-wheel-1.0-py3-none-any.whl
requests>=2  # listed twice
`;
    assert.deepEqual(requirementNames(text), [
        'django',
        'requests',
        'typing-extensions',
        'zope-interface',
        'pkg-from-url',
        'uvloop',
    ]);
});

test('requirementNames: pip-compile output, hashes on continuation lines', () => {
    const text = `#
# This file is autogenerated by pip-compile
#
certifi==2024.8.30 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via requests
idna==3.10 \\
    --hash=sha256:cccc
    # via requests
`;
    assert.deepEqual(requirementNames(text), ['certifi', 'idna']);
});

// A fake file system: absolute path -> contents.
function reader(files: Record<string, string>) {
    return async (file: string) => files[path.resolve(file)];
}

test('collectMainIncludes: a dev file that includes requirements.txt', async () => {
    const dev = '/repo/requirements-dev.txt';
    const text = `-r requirements.txt
-r requirements-test.txt
pytest>=8
requests==2.32.3
`;
    const result = await collectMainIncludes(dev, text, reader({
        '/repo/requirements.txt': 'requests==2.32.3\nidna>=3.0\n',
        '/repo/requirements-test.txt': 'coverage\n',
    }));
    // The test file is development requirements too: it stays in the dev group.
    assert.deepEqual(result.mainIncludes, [path.resolve('/repo/requirements.txt')]);
    // requests is listed by the dev file itself, so it is not taken back out.
    assert.deepEqual(result.inheritedPackages, ['idna']);
});

test('collectMainIncludes: follows the includes of what it includes, and survives a cycle', async () => {
    const dev = '/repo/requirements/dev.txt';
    const result = await collectMainIncludes(dev, '-r base.txt\nruff\n', reader({
        '/repo/requirements/base.txt': '-r common.txt\nfastapi\n',
        '/repo/requirements/common.txt': '-r base.txt\npydantic\n',
    }));
    assert.deepEqual(result.mainIncludes, [path.resolve('/repo/requirements/base.txt')]);
    assert.deepEqual(result.inheritedPackages, ['fastapi', 'pydantic']);
});

test('collectMainIncludes: an unreadable include contributes nothing', async () => {
    const result = await collectMainIncludes('/repo/requirements-dev.txt', '-r requirements.txt\npytest\n', reader({}));
    assert.deepEqual(result.mainIncludes, [path.resolve('/repo/requirements.txt')]);
    assert.deepEqual(result.inheritedPackages, []);
});

test('collectMainIncludes: no includes, nothing to do', async () => {
    const result = await collectMainIncludes('/repo/requirements-dev.txt', 'pytest\nruff\n', reader({}));
    assert.deepEqual(result, { mainIncludes: [], inheritedPackages: [] });
});

test('shellArg: quotes only what needs it', () => {
    assert.equal(shellArg('requirements.txt'), 'requirements.txt');
    assert.equal(shellArg('my deps/requirements.txt'), '"my deps/requirements.txt"');
});

test('convertCommands: runtime requirements', () => {
    assert.deepEqual(
        convertCommands({ hasPyproject: false, requirementsPath: 'requirements.txt', target: 'main' }),
        [INIT_COMMAND, 'uv add -r requirements.txt'],
    );
    assert.deepEqual(
        convertCommands({ hasPyproject: true, requirementsPath: 'requirements.txt', target: 'main' }),
        ['uv add -r requirements.txt'],
    );
    assert.equal(INIT_COMMAND, 'uv init --bare');
});

test('convertCommands: a dev import of a file that includes requirements.txt', () => {
    assert.deepEqual(
        convertCommands({
            hasPyproject: false,
            requirementsPath: 'requirements-dev.txt',
            target: 'dev',
            mainIncludes: ['requirements.txt'],
            inheritedPackages: ['idna', 'requests'],
        }),
        [
            INIT_COMMAND,
            'uv add -r requirements.txt',
            'uv add --dev -r requirements-dev.txt',
            'uv remove --dev idna requests',
        ],
    );
});

test('convertCommands: a dev import with nothing included, and a path with a space', () => {
    assert.deepEqual(
        convertCommands({ hasPyproject: true, requirementsPath: 'dev deps/requirements-dev.txt', target: 'dev' }),
        ['uv add --dev -r "dev deps/requirements-dev.txt"'],
    );
});

test('convertChoices: asks only when the name leaves room to', () => {
    assert.deepEqual(convertChoices('main').map(c => [c.label, c.target]), [['Convert', 'main']]);
    assert.deepEqual(convertChoices('dev').map(c => c.target), ['dev', 'main']);
    assert.deepEqual(convertChoices('other').map(c => c.target), ['main', 'dev']);
});

test('displayCommand: long commands are cut short with a count', () => {
    assert.equal(displayCommand('uv add -r requirements.txt'), 'uv add -r requirements.txt');
    const names = Array.from({ length: 40 }, (_, i) => `package-${i}`);
    const shown = displayCommand(`uv remove --dev ${names.join(' ')}`);
    assert.ok(shown.startsWith('uv remove --dev package-0 package-1 '));
    assert.match(shown, / … \(\+\d+ more\)$/);
    const hidden = Number(shown.match(/\+(\d+) more/)![1]);
    const listed = shown.replace(/ … .*$/, '').split(' ').length - 3;
    assert.equal(listed + hidden, names.length);
});

// The confirmation's one job: what it lists is what the button runs.
function assertListsEveryCommand(detail: string, commands: string[]) {
    for (const command of commands) {
        assert.ok(detail.includes(displayCommand(command)), `detail should list: ${command}\n---\n${detail}`);
    }
}

test('convertPrompt: requirements.txt in a folder with no pyproject.toml', () => {
    const commands = {
        main: [INIT_COMMAND, 'uv add -r requirements.txt'],
        dev: [INIT_COMMAND, 'uv add --dev -r requirements.txt'],
    };
    const prompt = convertPrompt({
        folderName: 'my-app',
        requirementsPath: 'requirements.txt',
        choices: convertChoices('main'),
        commands,
        mainIncludes: [],
    });
    assert.equal(prompt.message, 'Convert my-app to a uv project?');
    assertListsEveryCommand(prompt.detail, commands.main);
    assert.ok(!prompt.detail.includes('--dev'), 'a single-choice prompt lists only what it runs');
    assert.match(prompt.detail, /creates pyproject\.toml and nothing else/);
    assert.match(prompt.detail, /requirements\.txt is read, not changed\./);
});

test('convertPrompt: requirements.txt next to an existing pyproject.toml', () => {
    const prompt = convertPrompt({
        folderName: 'my-app',
        requirementsPath: 'requirements.txt',
        choices: convertChoices('main'),
        commands: { main: ['uv add -r requirements.txt'], dev: ['uv add --dev -r requirements.txt'] },
        mainIncludes: [],
    });
    assert.equal(prompt.message, 'Import requirements.txt into the uv project in my-app?');
    assert.ok(!prompt.detail.includes(INIT_COMMAND));
});

test('convertPrompt: a dev file lists both choices, dev first, and explains the include', () => {
    const commands = {
        main: [INIT_COMMAND, 'uv add -r requirements-dev.txt'],
        dev: [
            INIT_COMMAND,
            'uv add -r requirements.txt',
            'uv add --dev -r requirements-dev.txt',
            'uv remove --dev idna requests',
        ],
    };
    const prompt = convertPrompt({
        folderName: 'my-app',
        requirementsPath: 'requirements-dev.txt',
        choices: convertChoices('dev'),
        commands,
        mainIncludes: ['requirements.txt'],
        unsaved: true,
    });
    assert.equal(prompt.message, 'Where should the packages in requirements-dev.txt go?');
    assertListsEveryCommand(prompt.detail, commands.dev);
    assertListsEveryCommand(prompt.detail, commands.main);
    assert.ok(prompt.detail.indexOf('Dev Group runs') < prompt.detail.indexOf('Main Dependencies runs'));
    assert.match(prompt.detail, /includes requirements\.txt, so Dev Group first imports it into the project's dependencies, then takes those packages back out of the dev group\./);
    assert.match(prompt.detail, /unsaved changes to requirements-dev\.txt are saved first/);
});
